import React, { useRef } from 'react'; // Correct import
import { Text, View, Image, ScrollView, StyleSheet, ImageBackground, TouchableOpacity} from 'react-native'




const Favorites = () => {



  return (
    <ScrollView style={styles.elon} >
       <ImageBackground
       source={require('../../logo/sol7.jpg')} 

       style={styles.musk} 
       resizeMode="cover">
        <View style={styles.kick}>
              <Text style={styles.text}>Powerwall</Text>
              <Text style={styles.save} >Whole-Home Backup, 24/7</Text>
              </View>
              <TouchableOpacity style={styles.button}>
          <Text style={styles.day} >get started  </Text> 
          </TouchableOpacity>
          <TouchableOpacity style={styles.side}>
          <Text style={styles.miss} >Order With Solar</Text>
          </TouchableOpacity>
       </ImageBackground>

     
         <View style={styles.real}>
        <Text style={styles.big}>Power Your Home, Save Money </Text>
        <Text style={styles.bruh} >Powerwall is a compact home battery that stores{"\n"} energy generated by solar or from the grid. You can{"\n"} use this energy to power the devices and appliances{"\n"} in your home day and night, during outages or when{"\n"} you want to go off-grid. With customizable power{"\n"} modes, you can optimize your stored energy for{"\n"} outage protection, electricity bill savings and more.</Text>
        </View>
        
        <View style={styles.react}>
              <Text style={styles.stand}>Maximum Solar Production</Text>
              <Text style={styles.right}>Generate the most energy possible, even on roofs {"\n"}with complicated angles and intermittent sunlight.{"\n"} Glass solar tiles and architectural-grade steel tiles,{"\n"} vent covers and ridge caps come together to form a{"\n"} roof that is both durable and powerful. Combine your{"\n"} Solar Roof with Powerwall—a home battery featuring{"\n"} an integrated solar inverter for increased efficiency{"\n"} and dependable energy storage 24/7.</Text>
              </View>
              <View style={styles.gave}>
              <Image
              source={require('../../logo/sol.jpg')}
              style={styles.tiny}/>
              </View>
              <View style={styles.cash}>
              <Text style={styles.vist}>Customize Preferences</Text>
              <Text style={styles.energy}>Decide if you want to optimize your generated {"\n"}energy for savings, backup protection—or both.</Text>
              <Text style={styles.vist}>Monitor Energy Flow</Text>
              <Text style={styles.energy}>See how much energy your system is generating,{"\n"} how it’s being used and how much it’s helping you{"\n"} save.</Text>
              <Text style={styles.vist}>Get Urgent Alerts</Text>
              <Text style={styles.energy}>Receive updates on your system status and get{"\n"} alerts about grid outages or severe weather.</Text>
              </View>
              <View style={styles.soul} > 
       <Text style={styles.love}>Copyright © 2025 khalidmohd</Text>
       </View>  
        </ScrollView>
  )
}

const styles = StyleSheet.create({
  elon: {   
     flex: 1,
     alignContent: 'center',
     backgroundColor: '#000',

  },

  musk: {
    width: '100%', // Use responsive width
    height: 600, // Use responsive height
    justifyContent: 'center', // Space between items
    bottom: 22,
  },
  kick: {
    alignItems: 'center', // Center the text horizontally
    marginBottom: 150,

  },
  text: {
    color: '#fff',
    fontSize: 23,
    textAlign: 'center',
    fontWeight: '700',
  },
  save: {
    color: '#fff',
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '500',
    margin: 7,
  },
  button: {
    alignItems: 'center',
    fontWeight: '500',
    textTransform: 'capitalize',
    fontSize: 18,
    fontWeight: '600',
    width: 323,
    paddingVertical: 9, 
    borderColor: 'dodgerblue',
    borderWidth: 0.5,
    borderRadius: 17,        
    backgroundColor: '#2563eb',
    alignSelf: 'center',
    margin: 6,
  },
  side: {
    alignItems: 'center',
    fontWeight: '500',
    textTransform: 'capitalize',
    fontSize: 18,
    fontWeight: '600',
    width: 323,
    paddingVertical: 9, 
    borderColor: 'dodgerblue',
    borderWidth: 0.5,
    borderRadius: 17,        
    backgroundColor: '#2563eb',
    alignSelf: 'center',
    margin: 6,
  },
  sky: {
    width: '100%', // Use responsive width
    height: 600, // Use responsive height
    justifyContent: 'flex-start', // Space between items
    bottom: 22,

  },
  real: {
    alignItems: 'center',
    marginTop: 27,   
  },
  big: {
    color: '#00FFFF',
    fontSize: 21,
    fontWeight: '500',
  },
  bruh: {
    color: '#FFF',  
    fontSize: 16,
    marginTop: 11,
    fontWeight: '500',
  },
  react: {
    alignItems: 'center',
    marginTop: 21,
  },

  stand: {
    color: '#00FFFF',
    fontSize: 21,
    fontWeight: '600',
  },
  right: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
    marginTop: 11,
    textAlign: 'center',
  },
  tiny: {
    width: '99%', // Use responsive width
    height: 300, // Use responsive height
    justifyContent: 'center', 
    marginVertical: 20,
    alignSelf: 'center', // Center the image
  },
  gave: {
    alignItems: 'center', // Center content in this view
    marginVertical: 20,// Add some vertical spacing   
  },
  cash: {
    textAlign: 'right', // Center content in this view
    backgroundColor: '#000',
    marginTop: 20, // Add some vertical spacing
    justifyContent: 'center',
    paddingLeft: 11,
  },
  vist: {
    color: '#fff', // Center content in this view
    textTransform: 'capitalize',
    fontSize: 21,
    fontWeight: '600',
    marginTop: 30,    
    textAlign: 'left',
  },
  energy: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '500',
    marginTop: 10,
    textAlign: 'left',
  },
  soul: {
    marginTop: 32,
    alignItems: 'center',

    },
    love: {
      fontWeight: '500',
      marginBottom: 12,
      color: '#00FFFF',
      },
});


export default Favorites